import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import SessionProvider from "@/app/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='h-screen w-screen flex flex-col'>
					<nav className='h-24 md:h-32 w-full p-1 md:p-3 flex-initial'></nav>
					<div className='flex-1 w-full px-1 md:px-3 overflow-y-scroll'>
						<SessionProvider session={session}>
							<Providers>{children}</Providers>
						</SessionProvider>
					</div>
				</div>
			</body>
		</html>
	);
}
