import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-screen flex flex-col">
          <nav className="h-24 md:h-32 w-full p-1 md:p-3">
          </nav>
          <div className="flex-1 w-full px-1 md:px-3">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
